package modelo;
// default package
// Generated 13-ago-2014 20:16:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendarioId generated by hbm2java
 */
@Embeddable
public class CalendarioId implements java.io.Serializable {

	private String nombre;
	private Date startDate;
	private Date endDate;

	public CalendarioId() {
	}

	public CalendarioId(String nombre, Date startDate, Date endDate) {
		this.nombre = nombre;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Column(name = "NOMBRE", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "START_DATE", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalendarioId))
			return false;
		CalendarioId castOther = (CalendarioId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this
				.getNombre() != null && castOther.getNombre() != null && this
				.getNombre().equals(castOther.getNombre())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this
						.getStartDate() != null
						&& castOther.getStartDate() != null && this
						.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		return result;
	}

}
