package modelo;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "login_academia_bd")
public class Usuarios implements java.io.Serializable {

	private Integer idUsuario;
	private String user;
	private String password;
	private Date fechaUltimoLogin;

	public Usuarios() {
	}

	public Usuarios(String user, String password, Date fechaUltimoLogin) {
		this.user = user;
		this.password = password;
		this.fechaUltimoLogin = fechaUltimoLogin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUSUARIO", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "USER", nullable = false, length = 45)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ULTIMO_LOGIN", nullable = false, length = 19)
	public Date getFechaUltimoLogin() {
		return this.fechaUltimoLogin;
	}

	public void setFechaUltimoLogin(Date fechaUltimoLogin) {
		this.fechaUltimoLogin = fechaUltimoLogin;
	}

}
