SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LOGIN_ACADEMIA_BD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LOGIN_ACADEMIA_BD` ;
CREATE SCHEMA IF NOT EXISTS `LOGIN_ACADEMIA_BD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `LOGIN_ACADEMIA_BD` ;

-- -----------------------------------------------------
-- Table `LOGIN_ACADEMIA_BD`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOGIN_ACADEMIA_BD`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `LOGIN_ACADEMIA_BD`.`USUARIOS` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `USER` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `FECHA_ULTIMO_LOGIN` DATETIME NOT NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
